using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
public class DateModel
{
    // Data annotation specifying that the Id property is the primary key and is auto-generated by the database.
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    // Property representing the DATES information in the model.
    public int DATES { get; set; }
}