using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class WeekdayModel
{
    // Data annotation specifying that the Id property is the primary key and is auto-generated by the database.
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    // Property representing the WEEKDAYS information in the model.
    public string WEEKDAYS { get; set; }
}